version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: student_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: school_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:latest
    container_name: student_db_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql_data:
